### ISSUE TITLE
Modification to "analyze" method in Fuse Class

### ISSUE THREAD

**Issue by code-inspired** [Loilo/Fuse#1]
-- // Guard against "Undefined offset: 0" Error when $scoresLen == 0
-- // Guard against "Division By Zero" Error when $scoresLen == 0

$scoresLen = sizeof($scores);

                // Guide against "Undefined offset: 0" Error when $scoresLen == 0
                if($scoresLen > 0)
                $averageScore = $scores[0];
                
                for($i = 1; $i < $scoresLen; $i++) {
                    $averageScore += $scores[$i];
                }
                
                // Guide against "Division By Zero" Error when $scoresLen == 0
                if($scoresLen > 0)
                $averageScore /= $scoresLen;

Thanks for the PHP port. Its very useful for me. Please don't forget to Update us when Fuse.js has major changes. Regards

**Comment by Loilo** [comment]
Hey. Thanks for your contribution!

Would you mind creating a pull request for this? :)
