### ISSUE TITLE
Search is not working well

### ISSUE THREAD

**Issue by lunvjp** [Loilo/Fuse#10]
Right now I don't know how to set up the arguments for Search method:
======================================
Keywords: roofing
======================================
Current Results:
- Undertile External Water**proofing** Membranes
- **Roofing** Membrane
- Liquid water**proofing** membrane
- External water**proofing** membrane
- Liquid water**proofing** membrane
======================================
Expected Results:
- **Roofing** Membrane
======================================
Can someone help me sort this problem out? Thanks.

**Comment by Loilo** [comment]
It'd be useful to see the dataset you're using for search. I slightly disagree with your expected results, this is a fuzzy search library and its whole point is to show not only exact matches. I agree however that the exact matches would be nice to show on top.

That said, general rule of thumb about this kind of issue is: Fuse is a port. I have not developed the search algorithms, only translated them from another language.

If you're proficient in JavaScript, it would be helpful if you could test your case with the original library, on [the Fuse.js website](http://fusejs.io/). If the results are the same (which they absolutely should), [their repository](https://github.com/krisk/fuse) is the place to ask for algorithm improvements.

If you're not proficient in JavaScript and would be willing to provide your dataset to me, I could to the tests for you.

**Comment by lunvjp** [comment]
yeah..Thanks. You're right. it will be nicer to show on top. So the thing is we can change the results be like these below:
Expected results:
- **Roofing** Membrane
- Undertile External Waterp**roofing** Membranes
- Liquid waterp**roofing** membrane
- External waterp**roofing** membrane
- Liquid waterp**roofing** membrane
=====================
Do you know how to deal with the arguments?

**Comment by Loilo** [comment]
As I said, this is an issue with the search algorithm. Neither do I fully understand it nor am I willing to make changes that are not coming from Fuse.js directly.

The best place for you issue would be a feature request for Fuse.js, please open up an issue on [their repository](https://github.com/krisk/fuse). 🙂

**Comment by lunvjp** [comment]
Thanks for your time.

**Comment by Loilo** [comment]
My pleasure. If you need any more help with this, feel free to hit me up here.
