### ISSUE TITLE
Undefinex index 0 when using 'matchAllTokens' option

### ISSUE THREAD

**Issue by akrz** [Loilo/Fuse#12]
``` json
"type": "Whoops\\Exception\\ErrorException",
"message": "Undefined offset: 0",
"file": "/var/www/app/vendor/loilo/fuse/src/Fuse.php",
"line": 231,
```
The line is:
`$averageScore = $scores[0];`

But when the option matchAllTokens is used, $scores will be empty (in my tests)

I just initialized $averageScore = 0 and then check that index 0 is set in the $scores array. Seems ok?
I can make a pull request

**Comment by Loilo** [comment]
Thanks for offering the pull request. However, this is such a small change that I just implemented it myself. 🙂 

Thank you for pointing this bug out, it's fixed in the just releast v3.2.6!
