### ISSUE TITLE
Can't get a result

### ISSUE THREAD

**Issue by BooitsDaly** [Loilo/Fuse#16]
I have been trying to get a result from a search of my data set but I have yet to be able to get a result. I plugged my data set and options into the Fuse.js demo page and was able to get the expected results.

My data(small portion of it):
```
array(169) {
  [0]=>
  array(4) {
    ["name"]=>
    string(17) "Grace Watson Hall"
    ["description"]=>
    string(7) "GWH/025"
    ["mdo_id"]=>
    string(1) "3"
    ["coordinates"]=>
    array(2) {
      [0]=>
      float(-77.66901)
      [1]=>
      float(43.083652)
    }
  }
  [1]=>
  array(4) {
    ["name"]=>
    string(15) "Wallace Library"
    ["description"]=>
    string(7) "WAL/005"
    ["mdo_id"]=>
    string(1) "5"
    ["coordinates"]=>
    array(2) {
      [0]=>
      float(-77.676315)
      [1]=>
      float(43.083927)
    }
  }
```

initialization and search
```
$options = ["keys" => ["name","description","mdo_id"]];
$fuse =  new \Fuse\Fuse($data,$options);
$result = $fuse->search("Grace Watson Hall");
//result returns nothing and I get a 500 error
```

**Comment by Loilo** [comment]
500 error sounds like something really stupid on my side. :)
I'll take a look.

**Comment by Loilo** [comment]
I'm getting a correct result with your code. There must be either something that's missing from your code (could you post a full example file?) or in your environment (what PHP version are you running?).

**Comment by BooitsDaly** [comment]
This is the function I am using to format my data

`function getGeoData()
{
    $qs = "tag:Building";
    $qty = 1500;
    include_once("lib.php");
    $outerJSON = (object)[];
    $outerJSON->type = "FeatureCollection";
    $outerJSON->properties = array(
        "name" => "RIT Buildings"
    );
    $geoJSON = array();
    $objects = $data->response->docs;
    foreach ($objects as $obj) {
        $geoJSON[] = [
            "name" => $obj->name,
            "description" => $obj->description,
            "mdo_id" => $obj->mdo_id,
            "coordinates" => array($obj->longitude, $obj->latitude)
        ];
    }
    return $geoJSON;
}`

I then call this portion

`require_once './fuse/Fuse.php';
    $options = ["keys" => ["name","description","mdo_id"]];
    $fuse =  new \Fuse\Fuse($data,$options);
    var_dump(($data));
    $result = $fuse->search("Grace Watson Hall");
    var_dump($result);`

When printing out the fuse variable I am getting this:

`object(Fuse\Fuse)#175 (2) {
  ["options"]=>
  array(19) {
    ["location"]=>
    int(0)
    ["distance"]=>
    int(100)
    ["threshold"]=>
    float(0.6)
    ["maxPatternLength"]=>
    int(32)
    ["caseSensitive"]=>
    bool(false)
    ["tokenSeparator"]=>
    string(2) " +"
    ["findAllMatches"]=>
    bool(false)
    ["minMatchCharLength"]=>
    int(1)
    ["id"]=>
    NULL
    ["keys"]=>
    array(3) {
      [0]=>
      string(4) "name"
      [1]=>
      string(11) "description"
      [2]=>
      string(6) "mdo_id"
    }
    ["shouldSort"]=>
    bool(true)
    ["getFn"]=>
    string(24) "\Fuse\Helpers\deep_value"
    ["sortFn"]=>
    object(Closure)#176 (2) {
      ["this"]=>
      *RECURSION*
      ["parameter"]=>
      array(2) {
        ["$a"]=>
        string(10) "<required>"
        ["$b"]=>
        string(10) "<required>"
      }
    }
    ["tokenize"]=>
    bool(false)
    ["matchAllTokens"]=>
    bool(false)
    ["includeMatches"]=>
    bool(false)
    ["includeScore"]=>
    bool(false)
    ["verbose"]=>
    bool(false)
    ["isCaseSensitive"]=>
    bool(false)
  }
  ["list"]=>
  array(169) {
    [0]=>
    array(4) {
      ["name"]=>
      string(17) "Grace Watson Hall"
      ["description"]=>
      string(7) "GWH/025"
      ["mdo_id"]=>
      string(1) "3"
      ["coordinates"]=>
      array(2) {
        [0]=>
        float(-77.66901)
        [1]=>
        float(43.083652)
      }
    }
    [1]=>
    array(4) {
      ["name"]=>
      string(15) "Wallace Library"
      ["description"]=>
      string(7) "WAL/005"
      ["mdo_id"]=>
      string(1) "5"
      ["coordinates"]=>
      array(2) {
        [0]=>
        float(-77.676315)
        [1]=>
        float(43.083927)
      }
    }
    [2]=>
    array(4) {
      ["name"]=>
      string(19) "George Eastman Hall"
      ["description"]=>
      string(7) "EAS/001"
      ["mdo_id"]=>
      string(1) "6"
      ["coordinates"]=>
      array(2) {
        [0]=>
        float(-77.67503)
        [1]=>
        float(43.084694)
      }
    }`

**Comment by Loilo** [comment]
Oh, okay, I got it. You're requiring the `Fuse.php` directly. This won't work - Fuse is meant to be installed with Composer, which you apparently didn't do.

If you can't use Composer for some reason, you'd have to `require` *every* file in the `src` folder and its subfolders manually.

Please try it out and tell me if it worked. :)

**Comment by BooitsDaly** [comment]
That did it! Thank you!

**Comment by Loilo** [comment]
My pleasure. :)
