### ISSUE TITLE
Exceeding the max pattern length in search string doesn't throw error

### ISSUE THREAD

**Issue by vincemukiiri** [Loilo/Fuse#17]
I've found a case whereby the threshold of 0 is not being respected.

I initialise the Fuse object like so
```$fuseTest = new Fuse\Fuse([['name' => '8Th Street Clinic']], ['keys' => ['name'], 'threshold' => 0, 'includeScore' => true]);```

and search for
``` $fuseTest->search('Tumaini Medial Clinic (Miriga Mieru West)') ```

I get back
``` 
 [
     [
       "item" => [
         "name" => "8Th Street Clinic",
       ],
       "score" => 0.5,
     ],
] 
```

Which as you can see has a score of 0.5 but is still returned.

**Comment by vincemukiiri** [comment]
I've just realised that this happened because the default Max Pattern Length Provided is 32 and my search string exceeds it. Can be fixed by adding
```
$fuseTest = new Fuse\Fuse([['name' => 'eTh Street Clinic']], ['keys' => ['name'], 'threshold' => 0, 'includeScore' => true, 'maxPatternLength' => 64]);
```
But isn't this supposed to throw an error instead of returning a result?

**Comment by Loilo** [comment]
Thanks for the report. 👍 

No, it's not supposed to throw an error in that case – at least that's not what Fuse.js does. The Fuse.js website reports if you're using a pattern longer than the `maxPatternLength`:

![Screenshot of Fuse.js website showing the error](https://user-images.githubusercontent.com/1922624/53642028-05360080-3c31-11e9-8b7f-f57483cdf5b8.png)

But this is not due to it throwing an error, the underlying `fuse.search()` code still returns an empty array. The website probably just compares the search input with the `maxPatternLength` anyway.

**Comment by vincemukiiri** [comment]
Okay, well in that case shouldn't the search `$fuse->search()` also return an empty array? In the example I mentioned it still returned a result.

**Comment by Loilo** [comment]
Intuitively, I'd say yes, it should. However, this is just the ported behavior of Fuse.js which will return the exact same result.

You can try it out in the browser console on [fusejs.io](https://fusejs.io):

```js
const list = [{ name: '8Th Street Clinic' }]
const options = { keys:['name'], threshold: 0, includeScore: true }
const fuse = new Fuse(list, options)

fuse.search('Tumaini Medial Clinic (Miriga Mieru West)')
```

Given that the Fuse.js site states that "whenever the pattern exceeds the `maxPatternLength`, an error will be thrown" (which it doesn't), maybe this should be discussed [in their repo](https://github.com/krisk/Fuse).

**Comment by vincemukiiri** [comment]
Alright, I'll see if I can open an issue there. Thanks for the help, I love the library.

**Comment by vincemukiiri** [comment]
Here's the related issue in the Fuse.js repo krisk/Fuse#136

**Comment by Loilo** [comment]
Thanks for caring. :)
When Fuse.js gets out a release with that issue fixed, I should be pretty quick to port it over. 👍
