### ISSUE TITLE
兌換完面試後，沒有顯示在已兌換的面試列表（應該是快取問題）

### ISSUE THREAD

**Issue by wadehuangtw** [loilo/Fuse#25]

**Comment by loilo** [comment]
Sorry, can't read that. 🙁 Do you have a way to provide an English translation?

**Comment by wadehuangtw** [comment]
> Sorry, can't read that. 🙁 Do you have a way to provide an English translation?

@loilo I'm sorry, this issue from other repository, I post this issue to wrong place.
