### ISSUE TITLE
Update to latest Fuse.js library 6+

### ISSUE THREAD

**Issue by lennart-hendriksma** [loilo/Fuse#27]
Any change you might be updating this awesome project to the latest version of Fuse.js?

**Comment by loilo** [comment]
A chance certainly, it's just a matter of spare time. Fuse.js 3.6 -> 4.0 was pretty much a complete rewrite which means I'll have to basically port the entire library from scratch.

**Comment by loilo** [comment]
Side note: I'm currently working on this.

**Comment by loilo** [comment]
It's done! :)
