### ISSUE TITLE
What's Wrong With My Array?

### ISSUE THREAD

**Issue by teamcoltra** [Loilo/Fuse#4]
I have an array that outputs like this:
```
    [1106] => Array
        (
            [id] => 1106
            [url] => 3-brides-for-3-bad-boys-160488
            [description] => 0
            [title] => 3 Brides for 3 Bad Boys
            [author] => 3 Brides for 3 Bad Boys (mf)
            [author_lname] => Boys
            [language] => en
        )

    [1107] => Array
        (
            [id] => 1107
            [url] => 3-brisingr-3-12630502066281
            [description] => 0
            [title] => 3-Brisingr-3
            [author] => Unknown
            [author_lname] => 
            [language] => eng
        )

    [1108] => Array
        (
            [id] => 1108
            [url] => 3-claus-of-death-120101
            [description] => 0
            [title] => 3 Claus of Death
            [author] => Gayle Trent
            [author_lname] => Trent
            [language] => en
        )
```

But that results in:

> PHP Notice:  Undefined offset: -1 in /var/www/search/vendor/loilo/fuse/src/Bitap/matched_indices.php on line 24
> PHP Notice:  Undefined offset: -1 in /var/www/search/vendor/loilo/fuse/src/Bitap/matched_indices.php on line 24
> PHP Notice:  Undefined offset: -1 in /var/www/search/vendor/loilo/fuse/src/Bitap/matched_indices.php on line 24
> PHP Notice:  Undefined offset: -1 in /var/www/search/vendor/loilo/fuse/src/Bitap/matched_indices.php on line 24
> PHP Notice:  Undefined offset: -1 in /var/www/search/vendor/loilo/fuse/src/Bitap/matched_indices.php on line 24
> PHP Notice:  Undefined offset: -1 in /var/www/search/vendor/loilo/fuse/src/Bitap/matched_indices.php on line 24
> PHP Notice:  Undefined offset: -1 in /var/www/search/vendor/loilo/fuse/src/Bitap/matched_indices.php on line 24
> PHP Notice:  Undefined offset: -1 in /var/www/search/vendor/loilo/fuse/src/Bitap/matched_indices.php on line 24
> PHP Notice:  Undefined offset: -1 in /var/www/search/vendor/loilo/fuse/src/Bitap/matched_indices.php on line 24
> PHP Notice:  Undefined offset: -1 in /var/www/search/vendor/loilo/fuse/src/Bitap/matched_indices.php on line 24
> 

I was wondering what I need to do to? I have tried putting my array into a parent array but that changes everything to:

> /var/www/search# php search.php 
> PHP Notice:  Undefined offset: 0 in /var/www/search/vendor/loilo/fuse/src/Fuse.php on line 97
> PHP Notice:  Undefined offset: 0 in /var/www/search/vendor/loilo/fuse/src/Fuse.php on line 123

**Comment by Loilo** [comment]
That seems to be an incorrectly ported piece of code by me.

Do you still get a result when using the search, despite the error message?

**Comment by teamcoltra** [comment]
Right now my options are barebones:

```
$fuse = new \Fuse\Fuse($new, [
  "keys" => [ "title", "author" ]]);
```

**Comment by teamcoltra** [comment]
No results

**Comment by Loilo** [comment]
Do you get any results when performing the same search in [Fuse.js](http://fusejs.io/)?

**Comment by teamcoltra** [comment]
I just used their web demo and it works fine when I use json or my array.

**Comment by Loilo** [comment]
Hm. It's hard for to reproduce the error without having the whole dataset and the search query.

I know how the `PHP Notice` message emerges and how to avoid that, but you should still get a result...

**Comment by teamcoltra** [comment]
json file = https://pastebin.ca/3957763

```
require_once 'vendor/autoload.php';
$json = file_get_contents('jason.txt');
$decoded = json_decode($json,true);

$fuse = new \Fuse\Fuse($decoded, [
  "keys" => [ "title", "author" ]]);


$fuse->search('doc');
```

**Comment by teamcoltra** [comment]
I feel like I have found part of the issue, which is just me being dumb and not print_r($fuse->search('doc')); that's why I'm not getting any results.

*facepalm*

So if you already know the reason for the generated errors I think we solved it.

**Comment by Loilo** [comment]
Great. Was just about to say, I'm not having any issues with getting results from your code & data. 🙈

**Comment by teamcoltra** [comment]
The problem is the actual full sized json file is ~30MB large, https://github.com/robotomize/fujes handles it pretty quickly but this really chugs at it. That's not a complaint against the system, I don't think my use case is typical. That's probably a bit why I am having more of these issues.

**Comment by Loilo** [comment]
Possibly. I'm not very deep into the CS-related details on the algorithm. After all, this library is just a port. :)

Btw, new version (3.2.2) is out. Your PHP notices should be gone with that. (And I really should turn mine on for library development. 🙃 )

**Comment by Loilo** [comment]
If this solves your problem, feel free to close this issue. :)

**Comment by teamcoltra** [comment]
Yes it does, new update works great. Thanks Loilo!

**Comment by Loilo** [comment]
My pleasure.
