### ISSUE TITLE
Error that needs to be fixed 

### ISSUE THREAD

**Issue by nakbill** [Loilo/Fuse#6]
Hi
I am using your project that it is very useful but i noticed a problem that needs to be fixed.
In Fuse.php file at line 226 your code is
$averageScore = $averageScore / $scoresLen;

I noticed that sometimes the $scoresLen in my project is 0 so the the action of division prints out an error
I suggest adding the following in order to avoid this error
if($scoresLen !=0){
$averageScore = $averageScore / $scoresLen;
}
Best Regards

**Comment by Loilo** [comment]
Hey, thanks for the bug report.

Would you mind to provide a sample data set + search query where this happens? That would be pretty helpful since it then should happen in [Fuse.js](http://fusejs.io/) as well and I'd report it there.

**Comment by Hauuguu** [comment]
Also having the same issue. Simply installing via composer and using this code will produce the errors for division by 0 and undefined offset: 0.

```php
<?php
require_once 'vendor/autoload.php';

$fuse = new \Fuse\Fuse(
  [
    [
      "title" => "Old Man's War",
      "author" => "John Scalzi",
    ],
    [
      "title" => "The Lock Artist",
      "author" => "Steve Hamilton",
    ],
    [
      "title" => "HTML5",
      "author" => "Remy Sharp",
    ],
    [
      "title" => "Right Ho Jeeves",
      "author" => "P.D Woodhouse",
    ],
  ], [
    "tokenize" => true,
    "matchAllTokens" => true,
    "keys" => [
      [
        "name" => "title",
        "weight" => 0.3,
      ],
      [
        "name" => "author",
        "weight" => 0.7,
      ],
    ],
  ]);

var_dump($fuse->search('hamil')); 

?>
```

**Comment by Loilo** [comment]
Thanks for providing the example. 👍

I took a look at the same request for Fuse.js and they actually have division by zero as well in those situations. However, JavaScript won't throw an error in that case and the result ([`NaN`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/NaN)) will just be handled as "no results".

I'll add an additional check to avoid this error.
