### ISSUE TITLE
Fuse in Drupal

### ISSUE THREAD

**Issue by kaise-lafrai** [loilo/Fuse#69]
I am using this project on my local Drupal build. The Fuse array does not show a "Results" index in the array after the search is complete. Can you confirm that the results of the search should be in a "Results" index in the Fuse array?

**Comment by loilo** [comment]
The structure of search results depends on the options you feed into the `new Fuse` constructor, but I can confirm that none of the options causes them to be found in a `results` key.

This answers your specific question, so I'll close this issue. However, feel free to add more detailed information if you need help with anything.

**Comment by loilo** [comment]
You can take a look [at the docs](https://github.com/loilo/Fuse#usage) to see a typical example of a search call and its according result structure.
